---
name: Security Scan

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  
  group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
  
  cancel-in-progress: true

jobs:
  security-scan:
    name: Bandit Security Scan
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      
      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
          cache: poetry

      - name: Install dependencies
        run: make install-dev

      - name: Security scan
        run: make security-scan
